In [1]:
import numpy as np

1-Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array. 


In [7]:
n1=[2,3,4,5,6,7]
n2=np.array(n1)

In [8]:
n2

array([2, 3, 4, 5, 6, 7])

In [9]:
n2.ndim

1

3-Write a NumPy program to create a null vector of size 10 and update the sixth value to 11

In [45]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
x[6]=11
x

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

4-Write a NumPy program to reverse an array (first element becomes last)

In [48]:
b=np.arange(0,10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
c=b[::-1]
c

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

5-Write a NumPy program to create a 2d array with 1 on the border and 0 inside

In [58]:
q=np.ones((4,4))
q

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
q[1:-1,1:-1]=0
q

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

7-Write a NumPy program to append values to the end of an array

In [65]:
t=[2,3,4]
t

[2, 3, 4]

In [66]:
t=np.append(t,[[5,6,7],[8,9,10]])
t

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

9-Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements

In [67]:
x4=np.array([1,2,3])
print("Size of the array: ", x4.size)
print("Length of one array element in bytes: ", x4.itemsize)
print("Total bytes consumed by the elements: ", x4.nbytes)

Size of the array:  3
Length of one array element in bytes:  4
Total bytes consumed by the elements:  12


10-Write a NumPy program to test whether each element of a 1-D array is also present in a second array

In [69]:
a1 = np.array([0, 18, 290, 409, 660])
print("Array1: ",a1)
a2 = np.array([4,660,18])
print("Array2: ",a2)
print("Compare each element of a1 and a2")
print(np.in1d(a1, a2))

Array1:  [  0  18 290 409 660]
Array2:  [  4 660  18]
Compare each element of a1 and a2
[False  True False False  True]


11-Write a NumPy program to create an array of ones and an array of zeros

In [73]:
ones=np.ones(10)
print("array of ones =",ones)
zeros=np.zeros(5)
print("array of zeros =",zeros)

array of ones = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
array of zeros = [0. 0. 0. 0. 0.]


12-Write a NumPy program to create a new shape to an array without changing its data

In [78]:
x4 = np.array([1, 2, 3, 4, 5, 6])
y = np.reshape(x4,(3,2))
print(x4)
y

[1 2 3 4 5 6]


array([[1, 2],
       [3, 4],
       [5, 6]])

13-Write a NumPy program to change the data type of an array

In [82]:
u=np.array([30.5,40.7,5.2,6.5])
i=u.astype(int)
i

array([30, 40,  5,  6])

15-Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere


In [92]:
L=np.eye(5)
L

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])